### ISSUE TITLE
Makefile not outputting valid .wasm file

### ISSUE THREAD

**Issue by paperboygold** [ChillAndImprove/ThreagilePlus#16]
Hey I've been trying to compile `main.wasm` on multiple versions of Go (primarily 1.16.15 and 1.21.4). 

When I run your `main.wasm` (which came with the repo) there are no issues, but attempting `GOOS=js GOARCH=wasm go build -o main.wasm` myself will give me a binary that doesn't seem to work. 

The application throws the following error:
```
Error while parsing JSON-Object: TypeError: window.parseModelViaString is not a function
```

Could you share what flags you've been using to compile the `.wasm` file?

**Comment by ChillAndImprove** [comment]
Funnily enough, I've got the same problem.

**Comment by ChillAndImprove** [comment]
LoL, after one year fixed. The wasm_exec was too old.
