### ISSUE TITLE
mxGraph is deprecated 

### ISSUE THREAD

**Issue by ezavgorodniy** [ChillAndImprove/ThreagilePlus#36]
The links from README is leading into https://github.com/jgraph/mxgraph?tab=readme-ov-file, which is that development is stopped

**Comment by ChillAndImprove** [comment]
Thanks for pointing this out. Yes, mxGraph development has stopped. There's a new fork, MaxGraph, but it's still early in development and not as stable. For now, I'll continue using mxGraph as it still supports the necessary functions, despite some being deprecated, which I can fix in the future.
