### ISSUE TITLE
Contributors onboarding not clear

### ISSUE THREAD

**Issue by ezavgorodniy** [ChillAndImprove/ThreagilePlus#37]
The thing I wanted to do make the tool use the latest Threagile from master and I'm a bit struggling with getting it started on my machine (mainly because of lack of knowledge of wasm but anyway some docs would be nice to have)

**Comment by ChillAndImprove** [comment]
Hello ezavgorodniy,
could you let me know where exactly you're stuck? The process to compile Threagile using WebAssembly (wasm) is quite straightforward on Linux:

 - Clone the repository to access the version of the source code you need.
 - Navigate to the wasm/Threagile directory within the cloned repository.
 - Run the make command from this directory.

This should compile the Threagile tool using WebAssembly.
